const USER_FLAGGED = 'USER_FLAGGED';
const USER_REQUESTED = 'USER_REQUESTED';
const USER_MISSED = 'USER_MISSED';

const ISSUE_TYPE = {
  USER_FLAGGED,
  USER_REQUESTED,
  USER_MISSED,
};

export default ISSUE_TYPE;
